/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.CardLayout;

/**
 *
 * @author ilzi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelBotao = new javax.swing.JPanel();
        bt_Cadastro = new javax.swing.JButton();
        bt_Vendas = new javax.swing.JButton();
        bt_Pesquisar = new javax.swing.JButton();
        bt_CadastroExtra = new javax.swing.JButton();
        CardPrincipal = new javax.swing.JPanel();
        Card1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Card2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Card3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        PainelBotao.setBackground(new java.awt.Color(36, 47, 65));
        PainelBotao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_Cadastro.setBackground(new java.awt.Color(97, 212, 195));
        bt_Cadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        bt_Cadastro.setText("Cadastro");
        bt_Cadastro.setBorderPainted(false);
        bt_Cadastro.setDefaultCapable(false);
        bt_Cadastro.setFocusPainted(false);
        bt_Cadastro.setPreferredSize(new java.awt.Dimension(100, 30));
        bt_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CadastroActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 190, -1));

        bt_Vendas.setBackground(new java.awt.Color(97, 212, 195));
        bt_Vendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Vendas.setForeground(new java.awt.Color(255, 255, 255));
        bt_Vendas.setText("Vendas");
        bt_Vendas.setBorder(null);
        bt_Vendas.setBorderPainted(false);
        bt_Vendas.setFocusPainted(false);
        bt_Vendas.setFocusable(false);
        bt_Vendas.setPreferredSize(new java.awt.Dimension(100, 30));
        bt_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_VendasActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Vendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 190, -1));

        bt_Pesquisar.setBackground(new java.awt.Color(97, 212, 195));
        bt_Pesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Pesquisar.setText("Pesquisar/Editar");
        bt_Pesquisar.setBorder(null);
        bt_Pesquisar.setBorderPainted(false);
        bt_Pesquisar.setFocusPainted(false);
        bt_Pesquisar.setFocusable(false);
        bt_Pesquisar.setPreferredSize(new java.awt.Dimension(100, 30));
        bt_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PesquisarActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 190, -1));

        bt_CadastroExtra.setBackground(new java.awt.Color(97, 212, 195));
        bt_CadastroExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_CadastroExtra.setForeground(new java.awt.Color(255, 255, 255));
        bt_CadastroExtra.setText("Cadastro Extra");
        bt_CadastroExtra.setBorder(null);
        bt_CadastroExtra.setBorderPainted(false);
        bt_CadastroExtra.setFocusPainted(false);
        bt_CadastroExtra.setFocusable(false);
        bt_CadastroExtra.setPreferredSize(new java.awt.Dimension(100, 30));
        bt_CadastroExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CadastroExtraActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_CadastroExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, -1));

        CardPrincipal.setEnabled(false);
        CardPrincipal.setLayout(new java.awt.CardLayout());

        Card1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pata.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/client.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/produt.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/serv.png"))); // NOI18N

        javax.swing.GroupLayout Card1Layout = new javax.swing.GroupLayout(Card1);
        Card1.setLayout(Card1Layout);
        Card1Layout.setHorizontalGroup(
            Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(163, 163, 163))
                    .addGroup(Card1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27))))
        );
        Card1Layout.setVerticalGroup(
            Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(83, 83, 83)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        CardPrincipal.add(Card1, "tela1");

        Card2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pata.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/client.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/produt.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/serv.png"))); // NOI18N

        javax.swing.GroupLayout Card2Layout = new javax.swing.GroupLayout(Card2);
        Card2.setLayout(Card2Layout);
        Card2Layout.setHorizontalGroup(
            Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(179, 179, 179)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        Card2Layout.setVerticalGroup(
            Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(98, 98, 98)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        CardPrincipal.add(Card2, "tela2");

        Card3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/employees.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/raça.png"))); // NOI18N

        javax.swing.GroupLayout Card3Layout = new javax.swing.GroupLayout(Card3);
        Card3.setLayout(Card3Layout);
        Card3Layout.setHorizontalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel9)
                .addGap(185, 185, 185)
                .addComponent(jLabel10)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        Card3Layout.setVerticalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        CardPrincipal.add(Card3, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelBotao.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CadastroActionPerformed
        // TODO add your handling code here:
        //CardLayout cl = (CardLayout) CardPrincipal.getLayout();
        //cl.show(CardPrincipal, "tela1");
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card1);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
              
        
    }//GEN-LAST:event_bt_CadastroActionPerformed

    private void bt_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_VendasActionPerformed
        // TODO add your handling code here:
        //CardLayout cl = (CardLayout) CardPrincipal.getLayout();
        //cl.show(CardPrincipal, "tela2");
        
        
    }//GEN-LAST:event_bt_VendasActionPerformed

    private void bt_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PesquisarActionPerformed
        // TODO add your handling code here:
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card2);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
        
    }//GEN-LAST:event_bt_PesquisarActionPerformed

    private void bt_CadastroExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CadastroExtraActionPerformed
        // TODO add your handling code here:
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card3);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
        
    }//GEN-LAST:event_bt_CadastroExtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card1;
    private javax.swing.JPanel Card2;
    private javax.swing.JPanel Card3;
    private javax.swing.JPanel CardPrincipal;
    private javax.swing.JPanel PainelBotao;
    private javax.swing.JButton bt_Cadastro;
    private javax.swing.JButton bt_CadastroExtra;
    private javax.swing.JButton bt_Pesquisar;
    private javax.swing.JButton bt_Vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
