/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.CardLayout;

/**
 *
 * @author ilzi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelBotao = new javax.swing.JPanel();
        bt_Cadastro = new javax.swing.JButton();
        bt_Vendas = new javax.swing.JButton();
        bt_Pesquisar = new javax.swing.JButton();
        bt_CadastroExtra = new javax.swing.JButton();
        CardPrincipal = new javax.swing.JPanel();
        Card1 = new javax.swing.JPanel();
        bt_Cad_Produto = new javax.swing.JButton();
        bt_Cad_Cliente = new javax.swing.JButton();
        bt_Cad_Animal = new javax.swing.JButton();
        Card2 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Card3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("PeShopt ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        PainelBotao.setBackground(new java.awt.Color(36, 47, 65));
        PainelBotao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_Cadastro.setBackground(new java.awt.Color(97, 212, 195));
        bt_Cadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Cadastro.setForeground(new java.awt.Color(36, 47, 65));
        bt_Cadastro.setText("Cadastro");
        bt_Cadastro.setBorderPainted(false);
        bt_Cadastro.setDefaultCapable(false);
        bt_Cadastro.setFocusPainted(false);
        bt_Cadastro.setPreferredSize(new java.awt.Dimension(170, 40));
        bt_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CadastroActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 190, -1));

        bt_Vendas.setBackground(new java.awt.Color(97, 212, 195));
        bt_Vendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Vendas.setForeground(new java.awt.Color(36, 47, 65));
        bt_Vendas.setText("Vendas");
        bt_Vendas.setBorder(null);
        bt_Vendas.setBorderPainted(false);
        bt_Vendas.setFocusPainted(false);
        bt_Vendas.setFocusable(false);
        bt_Vendas.setPreferredSize(new java.awt.Dimension(170, 40));
        bt_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_VendasActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Vendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 190, -1));

        bt_Pesquisar.setBackground(new java.awt.Color(97, 212, 195));
        bt_Pesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Pesquisar.setForeground(new java.awt.Color(36, 47, 65));
        bt_Pesquisar.setText("Pesquisar/Editar");
        bt_Pesquisar.setBorder(null);
        bt_Pesquisar.setBorderPainted(false);
        bt_Pesquisar.setFocusPainted(false);
        bt_Pesquisar.setFocusable(false);
        bt_Pesquisar.setPreferredSize(new java.awt.Dimension(170, 40));
        bt_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PesquisarActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 190, -1));

        bt_CadastroExtra.setBackground(new java.awt.Color(97, 212, 195));
        bt_CadastroExtra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_CadastroExtra.setForeground(new java.awt.Color(36, 47, 65));
        bt_CadastroExtra.setText("Cadastro Extra");
        bt_CadastroExtra.setBorder(null);
        bt_CadastroExtra.setBorderPainted(false);
        bt_CadastroExtra.setFocusPainted(false);
        bt_CadastroExtra.setFocusable(false);
        bt_CadastroExtra.setPreferredSize(new java.awt.Dimension(170, 40));
        bt_CadastroExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CadastroExtraActionPerformed(evt);
            }
        });
        PainelBotao.add(bt_CadastroExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 190, -1));

        CardPrincipal.setEnabled(false);
        CardPrincipal.setLayout(new java.awt.CardLayout());

        Card1.setBackground(new java.awt.Color(153, 204, 255));

        bt_Cad_Produto.setBackground(new java.awt.Color(153, 204, 255));
        bt_Cad_Produto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Cad_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/produt.png"))); // NOI18N
        bt_Cad_Produto.setText("Produto");
        bt_Cad_Produto.setBorderPainted(false);
        bt_Cad_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Cad_ProdutoActionPerformed(evt);
            }
        });

        bt_Cad_Cliente.setBackground(new java.awt.Color(153, 204, 255));
        bt_Cad_Cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Cad_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/client.png"))); // NOI18N
        bt_Cad_Cliente.setText("Cliente");
        bt_Cad_Cliente.setBorderPainted(false);
        bt_Cad_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Cad_ClienteActionPerformed(evt);
            }
        });

        bt_Cad_Animal.setBackground(new java.awt.Color(153, 204, 255));
        bt_Cad_Animal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Cad_Animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pata.png"))); // NOI18N
        bt_Cad_Animal.setText("Animal");
        bt_Cad_Animal.setBorderPainted(false);
        bt_Cad_Animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Cad_AnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Card1Layout = new javax.swing.GroupLayout(Card1);
        Card1.setLayout(Card1Layout);
        Card1Layout.setHorizontalGroup(
            Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card1Layout.createSequentialGroup()
                        .addComponent(bt_Cad_Cliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Card1Layout.createSequentialGroup()
                        .addComponent(bt_Cad_Animal)
                        .addGap(160, 160, 160)
                        .addComponent(bt_Cad_Produto)
                        .addGap(117, 117, 117))))
        );
        Card1Layout.setVerticalGroup(
            Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(Card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cad_Animal)
                    .addComponent(bt_Cad_Produto))
                .addGap(82, 82, 82)
                .addComponent(bt_Cad_Cliente)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        CardPrincipal.add(Card1, "tela1");

        Card2.setBackground(new java.awt.Color(153, 204, 255));

        jButton12.setBackground(new java.awt.Color(153, 204, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pata.png"))); // NOI18N
        jButton12.setText("Animal");
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 204, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/produt.png"))); // NOI18N
        jButton11.setText("Produto");
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 204, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/client.png"))); // NOI18N
        jButton13.setText("Cliente");
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Card2Layout = new javax.swing.GroupLayout(Card2);
        Card2.setLayout(Card2Layout);
        Card2Layout.setHorizontalGroup(
            Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card2Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Card2Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(160, 160, 160)
                        .addComponent(jButton11)
                        .addGap(117, 117, 117))))
        );
        Card2Layout.setVerticalGroup(
            Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(Card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addGap(82, 82, 82)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPrincipal.add(Card2, "card3");

        Card3.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/employees.png"))); // NOI18N
        jButton1.setText("Funcionario");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/serv.png"))); // NOI18N
        jButton5.setText("Serviço");
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/raça.png"))); // NOI18N
        jButton7.setText("Raça");
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);

        javax.swing.GroupLayout Card3Layout = new javax.swing.GroupLayout(Card3);
        Card3.setLayout(Card3Layout);
        Card3Layout.setHorizontalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(Card3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(160, 160, 160)
                        .addComponent(jButton5)))
                .addGap(117, 117, 117))
        );
        Card3Layout.setVerticalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(82, 82, 82)
                .addComponent(jButton7)
                .addGap(54, 54, 54))
        );

        CardPrincipal.add(Card3, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CardPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelBotao.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CadastroActionPerformed
        // TODO add your handling code here:
        //CardLayout cl = (CardLayout) CardPrincipal.getLayout();
        //cl.show(CardPrincipal, "tela1");
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card1);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
              
        
    }//GEN-LAST:event_bt_CadastroActionPerformed

    private void bt_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_VendasActionPerformed
        // TODO add your handling code here:
        //CardLayout cl = (CardLayout) CardPrincipal.getLayout();
        //cl.show(CardPrincipal, "tela2");
        
        
    }//GEN-LAST:event_bt_VendasActionPerformed

    private void bt_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PesquisarActionPerformed
        // TODO add your handling code here:
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card2);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
        
    }//GEN-LAST:event_bt_PesquisarActionPerformed

    private void bt_CadastroExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CadastroExtraActionPerformed
        // TODO add your handling code here:
        
        CardPrincipal.removeAll();
        CardPrincipal.add(Card3);
        CardPrincipal.repaint();
        CardPrincipal.revalidate();
        
    }//GEN-LAST:event_bt_CadastroExtraActionPerformed

    private void bt_Cad_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Cad_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Cad_ProdutoActionPerformed

    private void bt_Cad_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Cad_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Cad_ClienteActionPerformed

    private void bt_Cad_AnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Cad_AnimalActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_bt_Cad_AnimalActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
       // TelaCadastroAnimal tela = new TelaCadastroAnimal();
       //tela.setVisible(true);
       new TelaCadastroAnimal().setVisible(true);
       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card1;
    private javax.swing.JPanel Card2;
    private javax.swing.JPanel Card3;
    private javax.swing.JPanel CardPrincipal;
    private javax.swing.JPanel PainelBotao;
    private javax.swing.JButton bt_Cad_Animal;
    private javax.swing.JButton bt_Cad_Cliente;
    private javax.swing.JButton bt_Cad_Produto;
    private javax.swing.JButton bt_Cadastro;
    private javax.swing.JButton bt_CadastroExtra;
    private javax.swing.JButton bt_Pesquisar;
    private javax.swing.JButton bt_Vendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
