/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Cliente;
import modeloDAO.ClienteDAO;


/**
 *
 * @author gustavo
 */
public class TelaAnimal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaAnimal() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        tabelaCliente.setRowSorter(new TableRowSorter(modelo));
        
        
        
        listarTabela();
    }
    
    public void listarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        modelo.setNumRows(0);
        
        ClienteDAO cdao = new ClienteDAO();
        
        cdao.listar().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCpf(),
                c.getNome(),
                c.getTelefone(),
                c.getEndereco(),
                c.getCidade(),
                c.getEstado()
                    
            });
        });
    
    }
    public void listarTabelaPorNome(String name){
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        modelo.setNumRows(0);
        
        ClienteDAO cdao = new ClienteDAO();
        
        cdao.listarPorNome(name).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCpf(),
                c.getNome(),
                c.getTelefone(),
                c.getEndereco(),
                c.getCidade(),
                c.getEstado()
                    
            });
        });
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Id_Animal = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        NomeAminal = new javax.swing.JLabel();
        idAnimal = new javax.swing.JTextField();
        nascAnimal = new javax.swing.JLabel();
        txtNasciemntoAnimal = new javax.swing.JTextField();
        SexoAnimal = new javax.swing.JLabel();
        CorAnimal = new javax.swing.JLabel();
        btn_salvarAnimal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCorAnimal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btn_excluirAnimal = new javax.swing.JButton();
        btn_editarAnimal = new javax.swing.JButton();
        BoxSexoAnimal = new javax.swing.JComboBox<>();
        NomeDono = new javax.swing.JLabel();
        txtDono = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 427));

        jLabel1.setFont(new java.awt.Font("TakaoPGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 43, 43));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANIMAL");

        Id_Animal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        Id_Animal.setText("ID");

        txtNomeAnimal.setToolTipText("");
        txtNomeAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAnimalActionPerformed(evt);
            }
        });

        NomeAminal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        NomeAminal.setText("NOME");

        idAnimal.setEditable(false);
        idAnimal.setToolTipText("");
        idAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAnimalActionPerformed(evt);
            }
        });

        nascAnimal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        nascAnimal.setText("NASCIMENTO");

        txtNasciemntoAnimal.setToolTipText("");
        txtNasciemntoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNasciemntoAnimalActionPerformed(evt);
            }
        });

        SexoAnimal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        SexoAnimal.setText("SEXO");

        CorAnimal.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        CorAnimal.setText("COR");

        btn_salvarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/salvar.png"))); // NOI18N
        btn_salvarAnimal.setText("Cadastrar");
        btn_salvarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarAnimalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel8.setText("TELEFONE");

        txtCorAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorAnimalActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pesquisa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "NASCIMENTO", "SEXO", "COR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        tabelaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);
        if (tabelaCliente.getColumnModel().getColumnCount() > 0) {
            tabelaCliente.getColumnModel().getColumn(0).setResizable(false);
            tabelaCliente.getColumnModel().getColumn(1).setResizable(false);
            tabelaCliente.getColumnModel().getColumn(2).setResizable(false);
            tabelaCliente.getColumnModel().getColumn(3).setResizable(false);
            tabelaCliente.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_excluirAnimal.setBackground(new java.awt.Color(215, 52, 52));
        btn_excluirAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/salvar.png"))); // NOI18N
        btn_excluirAnimal.setText("Excluir");
        btn_excluirAnimal.setToolTipText("");
        btn_excluirAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirAnimalActionPerformed(evt);
            }
        });

        btn_editarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/salvar.png"))); // NOI18N
        btn_editarAnimal.setText("Atualizar");
        btn_editarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarAnimalActionPerformed(evt);
            }
        });

        BoxSexoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "F", "M" }));

        NomeDono.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        NomeDono.setText("DONO");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telaPrincipal/imagens/pesquisa.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Id_Animal)
                                    .addComponent(idAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NomeAminal)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNomeAnimal)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(97, 97, 97))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salvarAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editarAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluirAnimal)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nascAnimal)
                                    .addComponent(txtNasciemntoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SexoAnimal)
                                    .addComponent(BoxSexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CorAnimal)
                                    .addComponent(txtCorAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeDono)
                                    .addComponent(txtDono))))
                        .addGap(175, 175, 175))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Animal)
                    .addComponent(NomeAminal))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nascAnimal)
                            .addComponent(SexoAnimal)
                            .addComponent(CorAnimal)
                            .addComponent(NomeDono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNasciemntoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxSexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvarAnimal)
                    .addComponent(btn_excluirAnimal)
                    .addComponent(btn_editarAnimal))
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAnimalActionPerformed

    private void idAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAnimalActionPerformed

    private void txtNasciemntoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNasciemntoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNasciemntoAnimalActionPerformed

    private void btn_salvarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarAnimalActionPerformed
        // TODO add your handling code here:
        
        Cliente c = new Cliente();
        ClienteDAO dao = new ClienteDAO();   
        
        c.setCpf(txtCpfcliente.getText());
        c.setNome(txtNomeAnimal.getText());
        c.setTelefone(txtCorAnimal.getText());
        c.setEndereco(txtNasciemntoAnimal.getText());
        c.setCidade(txtCidadeCliente.getText());
        c.setEstado((String) txtEstadoCliente.getSelectedItem());
        
        dao.inserir(c);
        
        idAnimal.setText("");
        txtCpfcliente.setText("");
        txtNomeAnimal.setText("");
        txtCorAnimal.setText("");
        txtNasciemntoAnimal.setText("");
        txtCidadeCliente.setText("");
        txtEstadoCliente.setSelectedItem("");
        
        listarTabela();
              
        
        
        
    }//GEN-LAST:event_btn_salvarAnimalActionPerformed

    private void txtCorAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorAnimalActionPerformed

    private void btn_excluirAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirAnimalActionPerformed
        // TODO add your handling code here:
        
        if(tabelaCliente.getSelectedRow() != -1){
            
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();
            
            c.setId((int) tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0));
            
                    
            dao.excluir(c);
            
            txtCpfcliente.setText("");
            txtNomeAnimal.setText("");
            txtCorAnimal.setText("");            
            txtNasciemntoAnimal.setText("");
            txtCidadeCliente.setText("");
            
            
            listarTabela();
            
        
        
        }
        
        
    }//GEN-LAST:event_btn_excluirAnimalActionPerformed

    private void btn_editarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarAnimalActionPerformed
        // TODO add your handling code here:
        
        if(tabelaCliente.getSelectedRow() != -1){
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();   

            c.setCpf(txtCpfcliente.getText());
            c.setNome(txtNomeAnimal.getText());
            c.setTelefone(txtCorAnimal.getText());
            c.setEndereco(txtNasciemntoAnimal.getText());
            c.setCidade(txtCidadeCliente.getText());
            c.setEstado((String) txtEstadoCliente.getSelectedItem());
            c.setId((int)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0));

            dao.atualizar(c);

            listarTabela();
            
        
        }
        
        
        
        
    }//GEN-LAST:event_btn_editarAnimalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listarTabelaPorNome(txtNomeAnimal.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        // TODO add your handling code here:
        
        if(tabelaCliente.getSelectedRow() != -1){
            
            idAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0).toString());
            txtCpfcliente.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 1).toString());
            txtNomeAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 2).toString());
            txtCorAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 3).toString());
            txtNasciemntoAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 4).toString());
            txtCidadeCliente.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 5).toString());
            //txtEstadoCliente.getSelectedItem((tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0x4).toString());
        
        }
        
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void tabelaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaClienteKeyReleased
        // TODO add your handling code here:
        
        if(tabelaCliente.getSelectedRow() != -1){
            
            idAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0).toString());
            txtCpfcliente.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 1).toString());
            txtNomeAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 2).toString());
            txtCorAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 3).toString());
            txtNasciemntoAnimal.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 4).toString());
            txtCidadeCliente.setText(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 5).toString());
            //txtEstadoCliente.getSelectedItem((tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0x4).toString());
        
        }
        
    }//GEN-LAST:event_tabelaClienteKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxSexoAnimal;
    private javax.swing.JLabel CorAnimal;
    private javax.swing.JLabel Id_Animal;
    private javax.swing.JLabel NomeAminal;
    private javax.swing.JLabel NomeDono;
    private javax.swing.JLabel SexoAnimal;
    private javax.swing.JButton btn_editarAnimal;
    private javax.swing.JButton btn_excluirAnimal;
    private javax.swing.JButton btn_salvarAnimal;
    public javax.swing.JTextField idAnimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nascAnimal;
    private javax.swing.JTable tabelaCliente;
    public javax.swing.JTextField txtCorAnimal;
    private javax.swing.JTextField txtDono;
    public javax.swing.JTextField txtNasciemntoAnimal;
    public javax.swing.JTextField txtNomeAnimal;
    // End of variables declaration//GEN-END:variables

    //private void listarTabela() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
